"""create obligations table

Revision ID: 22ede3f41ac5
Revises: b2e614961307
Create Date: 2026-09-30 21:32:26.430314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ede3f41ac5'
down_revision: Union[str, Sequence[str], None] = 'b2e614961307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('INVESTMENT_FUND', 'FAMILY', 'FRIEND', 'BANK', 'SACCO', 'MOBILE_LOAN', 'OTHER', name='obligationsource'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('obligation_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OUTSTANDING', 'PARTIALLY_PAID', 'PAID', name='obligationstatus'), server_default='OUTSTANDING', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_id'), 'obligations', ['id'], unique=False)
    op.create_index(op.f('ix_obligations_obligation_date'), 'obligations', ['obligation_date'], unique=False)
    op.create_index(op.f('ix_obligations_source'), 'obligations', ['source'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_user_id'), 'obligations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_user_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_source'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_obligation_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_id'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
