"""add reserved funds

Revision ID: 2ace7439e534
Revises: 495b02fda073
Create Date: 2026-09-30 12:45:24.418634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ace7439e534'
down_revision: Union[str, Sequence[str], None] = '495b02fda073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "financial_accounts",
    sa.Column(
        "reserved_funds",
        sa.Numeric(precision=15, scale=2),
        server_default="0.00",
        nullable=False,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_accounts', 'reserved_funds')
    # ### end Alembic commands ###
