"""track remaining investment principal

Revision ID: 2f8a150e6050
Revises: a0bab10fd291
Create Date: 2026-10-04 11:06:13.005386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8a150e6050'
down_revision: Union[str, Sequence[str], None] = 'a0bab10fd291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transactions', sa.Column('realized_gain_loss', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('investments', sa.Column('principal_remaining', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'principal_remaining')
    op.drop_column('investment_transactions', 'realized_gain_loss')
    # ### end Alembic commands ###
