"""create income

Revision ID: 495b02fda073
Revises: ae9782c763c5
Create Date: 2026-09-30 12:41:25.012633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495b02fda073'
down_revision: Union[str, Sequence[str], None] = 'ae9782c763c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('intended_period', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    op.create_index(op.f('ix_income_intended_period'), 'income', ['intended_period'], unique=False)
    op.create_index(op.f('ix_income_received_date'), 'income', ['received_date'], unique=False)
    op.create_index(op.f('ix_income_user_id'), 'income', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_user_id'), table_name='income')
    op.drop_index(op.f('ix_income_received_date'), table_name='income')
    op.drop_index(op.f('ix_income_intended_period'), table_name='income')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
