"""add savings funds

Revision ID: 54cbecee6c81
Revises: 4ab7d8e11cc3
Create Date: 2026-10-03 10:33:28.920460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cbecee6c81'
down_revision: Union[str, Sequence[str], None] = '4ab7d8e11cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_accounts', sa.Column('savings_funds', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_accounts', 'savings_funds')
    # ### end Alembic commands ###
