"""add major purchases and financing

Revision ID: 5b309e532ec0
Revises: d5d59f1030d5
Create Date: 2026-10-08 16:48:42.496942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b309e532ec0'
down_revision: Union[str, Sequence[str], None] = 'd5d59f1030d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_type', sa.Enum('CASH', 'FINANCED', name='purchasetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='majorpurchasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_purchases_user_id'), 'major_purchases', ['user_id'], unique=False)
    op.create_table('financing_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lender_name', sa.String(length=150), nullable=False),
    sa.Column('agreement_date', sa.Date(), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('financed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_term_months', sa.Integer(), nullable=True),
    sa.Column('expected_payment_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'CUSTOM', name='paymentfrequency'), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('custom_schedule_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SETTLED', 'CANCELLED', name='financingagreementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['major_purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financing_agreements_purchase_id'), 'financing_agreements', ['purchase_id'], unique=True)
    op.create_index(op.f('ix_financing_agreements_user_id'), 'financing_agreements', ['user_id'], unique=False)
    op.create_table('major_purchase_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('financing_agreement_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('DEPOSIT', 'INSTALMENT', 'LUMP_SUM', 'FINAL_SETTLEMENT', 'CASH_PURCHASE', name='majorpurchasepaymenttype'), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financing_agreement_id'], ['financing_agreements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['major_purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_purchase_payments_financing_agreement_id'), 'major_purchase_payments', ['financing_agreement_id'], unique=False)
    op.create_index(op.f('ix_major_purchase_payments_purchase_id'), 'major_purchase_payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_major_purchase_payments_user_id'), 'major_purchase_payments', ['user_id'], unique=False)
    op.create_table('major_purchase_payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('funding_source', sa.Enum('AVAILABLE_FUNDS', 'SAVINGS', name='paymentfundingsource'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['major_purchase_payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_purchase_payment_allocations_payment_id'), 'major_purchase_payment_allocations', ['payment_id'], unique=False)
    op.alter_column('investment_transactions', 'value_before',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.add_column('obligations', sa.Column('financing_agreement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_obligations_financing_agreement_id'), 'obligations', ['financing_agreement_id'], unique=False)
    op.create_foreign_key(None, 'obligations', 'financing_agreements', ['financing_agreement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_index(op.f('ix_obligations_financing_agreement_id'), table_name='obligations')
    op.drop_column('obligations', 'financing_agreement_id')
    op.alter_column('investment_transactions', 'value_before',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_major_purchase_payment_allocations_payment_id'), table_name='major_purchase_payment_allocations')
    op.drop_table('major_purchase_payment_allocations')
    op.drop_index(op.f('ix_major_purchase_payments_user_id'), table_name='major_purchase_payments')
    op.drop_index(op.f('ix_major_purchase_payments_purchase_id'), table_name='major_purchase_payments')
    op.drop_index(op.f('ix_major_purchase_payments_financing_agreement_id'), table_name='major_purchase_payments')
    op.drop_table('major_purchase_payments')
    op.drop_index(op.f('ix_financing_agreements_user_id'), table_name='financing_agreements')
    op.drop_index(op.f('ix_financing_agreements_purchase_id'), table_name='financing_agreements')
    op.drop_table('financing_agreements')
    op.drop_index(op.f('ix_major_purchases_user_id'), table_name='major_purchases')
    op.drop_table('major_purchases')
    # ### end Alembic commands ###
