"""add internal flag to ledger entries

Revision ID: a0b2f3ce8016
Revises: 2ace7439e534
Create Date: 2026-09-30 19:33:03.695627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b2f3ce8016'
down_revision: Union[str, Sequence[str], None] = '2ace7439e534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('is_internal', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_ledger_entries_is_internal'), 'ledger_entries', ['is_internal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_is_internal'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'is_internal')
    # ### end Alembic commands ###
