"""link obligations to expenses

Revision ID: c094a76c429a
Revises: 22ede3f41ac5
Create Date: 2026-10-02 16:01:33.757195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c094a76c429a'
down_revision: Union[str, Sequence[str], None] = '22ede3f41ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_obligations_expense_id'), 'obligations', ['expense_id'], unique=False)
    op.create_foreign_key(None, 'obligations', 'expenses', ['expense_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_index(op.f('ix_obligations_expense_id'), table_name='obligations')
    op.drop_column('obligations', 'expense_id')
    # ### end Alembic commands ###
